BASE_URL = "https://www.saucedemo.com/"
username_id = "user-name"
password_id = "password"
login_button_id = "login-button"
title_name = "title"
user_standart = "standard_user"
user_locked_out = "locked_out_user"
user_problem = "problem_user"
user_perf_glitch = "performance_glitch_user"
password_correct = "secret_sauce"
errorMessage_xpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage_text = "Epic sadface: Username and password do not match any user in this service"
errorMessage_empty_username_text = "Epic sadface: Username is required"
errorMessage_empty_password_text = "Epic sadface: Password is required"
errorMessage_lockout_user_text = "Epic sadface: Sorry, this user has been locked out."
errorMessage_not_as_expected = "Error message is not as expected"
add_backpack_id = "add-to-cart-sauce-labs-backpack"
remove_backpack_id = "remove-sauce-labs-backpack"
